{
 "title": "Network Speed Dash",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network",
    "query": "label_values(download_speed, network)"
   }
  ]
 },
 "panels": [
  {
   "title": "upload bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "upload_speed{network=~\"$network\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "upload bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "upload_bandwidth{network=~\"$network\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "download bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "download_speed{network=~\"$network\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "download bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "download_bandwidth{network=~\"$network\"}",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "ping",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ping_latency{network=~\"$network\"}",
     "legendFormat": "{{network}}"
    }
   ]
  }
 ]
}