scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      # todo this still isnt being scraped properly
      - targets: ['pushgateway:9091']
